version: 2.1
jobs:
  chromatic-deployment:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - run: yarn chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}

workflows:
  chromatic-deploy:
    jobs:
      - chromatic-deployment